---
title: "Lecture 3 Script Template"
author: "Jiaxi Li"
date: "2025-09-04"
output: pdf_document
---

```{r setup, include=FALSE}
# This is global set up for all later chunks
knitr::opts_chunk$set(echo = TRUE)
```

## Everything is an object

```{r}
# A simple data frame
d = data.frame(x = 1:2, y = 3:4) 
class(d)
```

```{r}
# Convert to matrix
m = 
# Convert to list
l = 
  
# Convert to numerical? character?

# Our previous factor
fact_groups = sample(letters,10,replace=T)
# Covert to other types. Do they work?
as.integer(fact_groups)
```

```{r}
# Why this does not work?
lm(y~x)

# Different ways to conduct lm, regress y on x

```

```{r}
# A new data frame!
d2 = data.frame(x = rnorm(10), y = runif(10))
```

```{r}
# We can do lm for both d and d2

# Summary here shows more details of lm result
# Do you remember what we get from summary with `summary(mtcars$mpg)`?
summary(lm(y~x,data=d2))
# Try ?summary to found out
```

## Everything has a name

```{r}
# Some naming problems
TRUE = 1
```

```{r}
# Why shouldn't we create this function?
pi = function(q,p,mc){
  q*p - q*mc
}

# Remove only the pi function
rm(pi)
```

```{r}
# Naming with c might not be a good idea, but R is smart enough now
c(1,2,3)
c = 2
# remove the saved c
rm(c)
```

```{r}
# Try to load these packages, what do you see?
library(dplyr)
library(data.table)
library(ggplot2)
```

```{r}
# Assignment to use a function from a specific package
filter = stats::filter
```

## Clearn up

```{r}
# Cleaning up
A = 1
B = 2
D = 3
# I do not use C and D here, you can check why by ?C and ?D

# remove all but a few key objects
# rm(list = setdiff(ls(), c("keep_this", "and_this")))
# Try to remove all but A

# free unused RAM
gc()
```
