---
title: "Lecture 2 Script Template"
author: "Jiaxi Li"
date: "2025-08-26"
output: pdf_document
---

```{r setup, include=FALSE}
# This is global set up for all later chunks
knitr::opts_chunk$set(echo = TRUE)
```

## Basic Operations

```{r}
# Here is out first vector
first_vec = 
first_vec
```

```{r}
# Try using : to create vector

# concatenate numbers to make a vector

```

```{r}
# Add single number to a vector, what does that do?
# How about adding a vector to a number?

```

```{r}
# Now, add a vector to a vector of same length
first_vec
6:10
first_vec + 6:10
```

```{r}
# What happens if two vectors added have different length?
first_vec
6:9
first_vec + 6:9
```

```{r}
# What would be the result of this one?

```

```{r}
# `c` can be used to create other type of vectors. More in Lecture 2.
c(1,2,5,12,1.4)
c("Blue", "Beige", "Black", "Brown")
```

```{r}
# other ways to work with vector



```

## Data Types

### Character

```{r}
# Try to put in your name here
my_name    = ""
first_name = ""
last_name  = ""

# `class` can check the data type

```

```{r}
class(first_vec)

# Now, check the length of the numeric vector

```

```{r}
# Same length function can work for character (vector) too
# What does it do?
my_name

```

```{r}
# How about nchar
my_name

```

```{r}
# Now concatenate two char (vectors)
c(first_name,last_name)
nchar(c(first_name,last_name))
```

```{r}
# `==` can be used to compare things, more about this in logic data type section
# Type your full name again here
also_my_name = '' # We are using ' instead of " here
my_name == also_my_name

# Type lower case of your name here
Lowercase_my_name = ''
my_name == Lowercase_my_name
```

```{r}
# pasting characters
first_name
last_name
paste(first_name,last_name)

# try paste0 and separate with -, \


c(first_name,last_name)
c(first_name,last_name) == paste(first_name,last_name)
first_name + " " + last_name
```

```{r}
# cat is to paste together and print
cat(first_name,last_name)
```

```{r}
# Auto printing vs. forced printing
my_name
print(my_name)

# Things inside of functions/loop are considered non-interactive contexts
nchar(my_name)
nchar(print(my_name))
for (j in 1) {my_name}
for (j in 1) {print(my_name)}
```

```{r}
# Change to upper case and lower case
toupper(c(first_name,last_name))
?(c(first_name,last_name))
```

### Numeric

```{r}
tolower(2)
```

```{r}
# Some special numeric values
class(Inf)
class(-Inf)
class(NaN)
```

### Logical

```{r}
R_is_fun  = TRUE
R_is_hard = FALSE
R_is_fun  == T
R_is_fun  == true
```

```{r}
# Math comparison

```

```{r}
# `& |` operations

```

```{r}
# `!` for negation

```

```{r}
# `%in%` checks whether a single element is in a vector
2 %in% c(1,2,3,4)

# test if 5 is in the vector c(1,2,3,4)

# test if 5 is NOT in the vector c(1,2,3,4)
```

```{r}
# NA vs. NaN
class(NA)
NA+1
is.na(NA)
is.nan(NA)
is.na(NaN) # This is a little strange, but good to know
```

### Complex

```{r}
# We will rarely use it
i
3i
1+2i
# i is the imaginary i, if you put a number in front of it
```

## Data Structure

### Vector

```{r}
# Now, formally working with vector using `c`
numeric_grades = c(90,75,95,85,100,60,76)
letter_grades  = c("A-","C","A","B","A","D","C")
mixed_grades   = c("A", 95,"B",85,"C",75)
```

```{r}
# Add names to vector, I rarely use this
names(numeric_grades) = c("Student 1","Student 2","Student 3",
                          "Student 4","Student 5","Student 6",
                          "Student 7")
```

```{r}
# Indexing
some_numbers = c(27,22,94)
some_numbers[1]
```

### List

```{r}
# What is the difference between vector and list?
TestList = list(c("Jiaxi","Li"),1:5,sample(c(TRUE,FALSE),20,replace=T))

# Indexing for list
TestList
```

```{r}
# some examples we worked through in class:
names(TestList) = c("my_name","numbers","logicals")
TestList[1][1]
TestList[1][[1]]
big_list <- list(list(c("Jiaxi","Li"),1:5,sample(c(TRUE,FALSE),20,replace=T)),c(1,2))
big_list[[1]]
big_list[1]
# Sequential indexing
big_list[[1]][2]
```

```{r}
names(letter_grades) = paste("Student",1:length(letter_grades))
grade_list = list(names(numeric_grades),numeric_grades,letter_grades)
grade_list

# names for list
names(grade_list) = c("studentNames","numericGrade","letterGrade")

# names can be used as index!
grade_list[["letterGrade"]]

grade_list["letterGrade"]
```

### Matrix

```{r}
# Do you notice how R make a vector into matrix?
num_mat = matrix(1:9,ncol=3)
# Names for row and col
colnames(num_mat) = paste("Col",1:ncol(num_mat))
rownames(num_mat) = paste("Row",1:nrow(num_mat))
num_mat
```

```{r}
num_mat2 = matrix(1:9,ncol=3,byrow = T)
num_mat2
```

### Data.frame

```{r}
class(mtcars)

head(mtcars)

names(mtcars)
```

```{r}
# Usually, we do not really want a row name.
# Instead, we want a separate column storing the names
# add make/model to the data frame as a column
mtcars$makemodel = rownames(mtcars)

# Remove the row names
rownames(mtcars) = NULL
```

```{r}
# Five number summary


mpgvec = mtcars$mpg
# Row selecting and indexing with data frame
# Select mtcars rows that mpgvec > median(mpgvec) and columns == 3
testvec <- mtcars[]
```

### Factors

```{r}
fact_groups = letters[sample(1:26,10,replace=T)]
fact_groups2 = sample(letters,10,replace=T) # two ways of writing the same command
```

```{r}
# Now, convert as factors
fact_groups = factor(fact_groups,levels=letters)
fact_groups = factor(fact_groups,levels=rev(letters))
# Factor with specified levels
fact_groups = factor(fact_groups, levels=c("a","e","i","o","u","y"))
# why are we getting NAs?
```
